# Generated by Django 2.1.7 on 2019-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyuitest', '0003_url_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_manage',
            name='createTime',
            field=models.CharField(default='2019-4-20', max_length=32),
        ),
        migrations.AddField(
            model_name='url_manage',
            name='creator',
            field=models.CharField(default='hill', max_length=32),
        ),
    ]
