# Generated by Django 2.1.7 on 2019-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyuitest', '0004_auto_20190520_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_manage',
            name='createTime',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='url_manage',
            name='creator',
            field=models.CharField(max_length=32),
        ),
    ]
